### ISSUE TITLE
How to migrate from a Docker Compose installation to a new Overleaf Toolkit instance?

### ISSUE THREAD

**Issue by HuengchI** [overleaf/toolkit#147]
Hey folks, I am seeking suggestions on how to migrate from a legacy Docker Compose installation to a new Overleaf Toolkit instance. I have already attempted to copy the data directory, but the application is refusing to start due to an incompatible version of mongo.

Here is my docker-compose.yaml file:

```yaml
version: '2.2'
services:
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex:3.1
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - /data/overleaf/sharelatex_data:/var/lib/sharelatex
            - /data/overleaf/sharelatex_texlive:/usr/local/texlive
        environment:

            SHARELATEX_APP_NAME: Overleaf Community Edition

            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex

            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'


            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

            SHARELATEX_SECURE_COOKIE: 'true'
            SHARELATEX_BEHIND_PROXY: 'true'


    mongo:
        restart: always
        image: mongo:4.0
        container_name: mongo
        expose:
            - 27017
        volumes:
            - /data//overleaf/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis:5
        container_name: redis
        expose:
            - 6379
        volumes:
            - /data/overleaf/redis_data:/data

```

Thank you!
