### ISSUE TITLE
Support container_name modification

### ISSUE THREAD

**Issue by Ezimkin** [overleaf/toolkit#247]
Hi as far as I can tell there is no way to specify the `container_name` value without manually modifying the following compose file under `lib/`. I think that this would be a nice feature to include in `config/overleaf.rc` to allow for multiple toolkit or custom `docker-compose.yml` files of the main `overleaf/overleaf` to be deployed to the same docker daemon for testing purposes.
https://github.com/overleaf/toolkit/blob/e8b536cad7b89ccf6fb53d40f3a97c4a7fa8d32b/lib/docker-compose.base.yml#L8

**Comment by AnzhiZhang** [comment]
You need to create a `docker-compose.override.yml` file.

See https://github.com/overleaf/toolkit/blob/master/doc/configuration.md#the-docker-composeoverrideyml-file

A quick example

```yml
services:
    sharelatex:
        container_name: overleaf-sharelatex
    mongo:
        container_name: overleaf-mongo
    redis:
        container_name: overleaf-redis
```
