### ISSUE TITLE
How I can use podman-compose (podman.socket) instead of docker?

### ISSUE THREAD

**Issue by ThomasGehPunkt** [overleaf/toolkit#330]
Hello,

the server we'll have to rollout the toolkit based overleaf intance will have podman.socket instead of docker. 

How I can change the composing that it'll uses podman instead of docker?

Thanks for some hint too.

Best.

**Comment by Falk358** [comment]
Regarding the selinux issue, this fixed it for me without needing to use `chcon`:

under `lib/docker-compose.base.yml` change the volume path mapping to include `:Z` at the end:

```yaml
  sharelatex:
    restart: always
    image: "${IMAGE}"
    container_name: sharelatex
    volumes:
      - "${OVERLEAF_DATA_PATH}:${OVERLEAF_IN_CONTAINER_DATA_PATH}:Z" # add :Z here
    ports:
      - "${OVERLEAF_LISTEN_IP:-127.0.0.1}:${OVERLEAF_PORT:-80}:80"
```
do the same for the volume definition in `docker-compose.mongo.yml` and `docker-compose.redis.yml`


short explanation:

> Two suffixes :z or :Z can be added to the volume mount. These suffixes tell Docker to relabel file objects on the shared volumes. The 'z' option tells Docker that the volume content will be shared between containers. Docker will label the content with a shared content label. Shared volumes labels allow all containers to read/write content. The 'Z' option tells Docker to label the content with a private unshared label. Private volumes can only be used by the current container.

This tells selinux to use the correct context labelling for the folder on your os (which is mounted inside the docker container)
