### ISSUE TITLE
SHARELATEX_PORT in overleaf.rc is not respected.

### ISSUE THREAD

**Issue by shriniwas26** [overleaf/toolkit#47]
## Steps to Reproduce

1. Follow the instructions in the toolkit document to get overleaf server started (in blocking mode, without -d option)
2. Stop the service (Ctrl-C)
3. Change config in overleaf.rc for SHARELATEX_PORT from 80 to 8001
4. Restart using "bin/up" script

## Expected Behaviour

http://localhost:8001 should show the overleaf page now. 

## Observed Behaviour

1. http://localhost/ now shows "nginx / bad gateway"
2. http://localhost:8081 does not load any page.  

## Context

I am trying to deploy overleaf on a server which already uses port 80 for another application. With the configuration options not respected, this seems difficult to do. 

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by ShaneKilkelly** [comment]
Hi, could you please run `bin/doctor` and paste the output in a comment here? 

Also, could you ensure you are using the latest version of the toolkit code (by running `bin/upgrade`)

Lastly, could you try running `bin/down` and then `bin/up`, and checking to see if this solves the problem? I have a suspicion that the config change may not be applied under some circumstances, just by running `bin/up`.

Thanks!

**Comment by ShaneKilkelly** [comment]
Also, I notice in your comment, that you change the port variable to `8001`, but are testing `http://localhost:8081`, which are different. I presume this is a typo, but it would be worth double-checking that the port is set correctly :)

**Comment by shriniwas26** [comment]
Sorry, there is a typo in my comment. Tried it with another port now, port number 5100. Please find attached the doctor output. 
First I stopped it using ./bin/stop, changed the port to 5100 and then started it using ./bin/up. Even after doing this I get:

[doctor_output.txt](https://github.com/overleaf/toolkit/files/6278277/doctor_output.txt)
 502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by ShaneKilkelly** [comment]
Thanks! 

To be clear, in this case, you get `Bad Gateway` on port `5100` ?, or on the default port? (`80`)

**Comment by shriniwas26** [comment]
Port `5100`, not the default port. But I just figured, if I reload it a couple of times, it starts working, without ever touching the terminal. But doesn't work until I have made at least one unsuccessful refresh.

**Comment by ShaneKilkelly** [comment]
Thanks for the confirmation. That's a bit strange. I wonder if it's just taking a while for the web service inside the container to come alive?.

However, it seems that the `SHARELATEX_PORT` option does work?

**Comment by shriniwas26** [comment]
Yes, the `SHARELATEX_PORT` option by itself works, but the "bad gateway" error only comes up with custom ports, not on the default port. I just confirmed. Of course it is your decision to either close this issue or let it be open. :)

**Comment by ShaneKilkelly** [comment]
Ah, I see, thanks for the clarification! I'll take a look and see if I can figure out what could be going wrong there.

**Comment by ShaneKilkelly** [comment]
I've tested this locally. Regardless of whether the port is set to it's default value, or it's set to a custom value - in both cases there is a short period of time in which the server will respond with 502 "Bad Gateway", and then start serving requests correctly.

This is a known behaviour, and stems from the internal nginx server being ready before the main web server process. 

I will close this issue, and we can re-open it if we get further reports of a behavioural difference between default and non-default ports.

**Comment by TheLoki2020** [comment]
Hi,
I followed most of the steps and changes mentioned, but when I try to start the server on port 8585, or any other port, I get server refused to connect.
I have other services running on the same virtual machine which I can access them. I tried running the `bin/doctor` and I get the same as @shriniwas26.
I don't get what I'm doing wrong.

**Comment by Teddy-van-Jerry** [comment]
I encountered the same problem setting the port to be 6000, with the output of `doctor` similarly.
```yml
====== Overleaf Doctor ======
- Host Information
    - Linux
    - Output of 'lsb_release -a':
            No LSB modules are available.
            Distributor ID:	Ubuntu
            Description:	Ubuntu 20.04 LTS
            Release:	20.04
            Codename:	focal
- Dependencies
    - bash
        - status: present
        - version info: 5.0.17(1)-release
    - docker
        - status: present
        - version info: Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
    - docker-compose
        - status: present
        - version info: docker-compose version 1.25.0, build unknown
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 8.30
    - perl
        - status: present
        - version info: 5.030000
    - awk
        - status: present
        - version info: GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
    - openssl
        - status: present
        - version info: OpenSSL 1.1.1f  31 Mar 2020
- Docker Daemon
    - status: up
====== Configuration ======
- config/version
    - status: present
    - version: 3.0.1
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_LISTEN_IP: 127.0.0.1
        - SHARELATEX_PORT: 6000
        - MONGO_ENABLED: true
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 127.0.1.1
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 127.0.1.1
        - TLS_PORT: 443
- config/variables.env
    - status: present
====== Warnings ======
- None, all good
====== End ======
```
@TheLoki2020 Have you figured out where the problem lies?
